#!/bin/sh
echo "Running ESLint"
eslint $(git diff --cached --name-only --diff-filter=ACMR | grep '\.js$\|\.ts$\|\.tsx$') --fix

echo "Running Prettier"
prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown

git update-index --again
echo "Pre-commit hook finished"
